[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake_my_score = "GP4V3sVgGuqTWAbmBn6T6ZCxtzBE2o5zsudYQS1YzjGQ"
[programs.devnet]
stake_my_score = "GP4V3sVgGuqTWAbmBn6T6ZCxtzBE2o5zsudYQS1YzjGQ"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
